language: swift
osx_image: xcode12
xcode_project: Mocca.xcodeproj
script:
  - xcodebuild -scheme Mocca -workspace Mocca.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.0,name=iPhone SE (2nd generation)' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1faa935e-2a27-4d49-bd3d-fa0bfbf8ba2f